spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/paymentsystem?currentSchema=payment_system
    username: "user"
    password: "pass"
  jpa:
    show-sql: true
    properties.hibernate:
      format_sql: true
      generate_statistics: true
  data:
    rest:
      base-path: /api
  liquibase:
    change-log: classpath:db/changelog-master.xml